### ISSUE TITLE
Error in elastic search

### ISSUE THREAD

**Issue by mcardle** [praxisdigital/moodle-local_datacleaner#3]
https://51a89e091a9d49299f9063ae7c34d164.eu-central-1.aws.cloud.es.io:9243/app/discover#/doc/fdbd9050-6c16-11e9-8f83-ebf44a0e1262/filebeat-7.17.2-2023.06.30-000067?id=CUwtL4kBD0gYbRsGuq1X

![Image](https://github.com/praxisdigital/moodle-local_datacleaner/assets/4198807/42c33027-6105-4dbf-9716-8ac101bacc3a)

**Comment by sampraxis** [comment]
Morris couldn't upgrade properly and cause local_morris web service API to failed.


![Image](https://github.com/praxisdigital/moodle-local_datacleaner/assets/41996743/0129553b-7833-455b-8db7-f80a63866634)
